export const products = [
  {
    "id": "13",
    "resName": "citybalcony",
    "name": "صحن خضار وزيتون ومخلل",
    "name2": "Mixed Vegetables, Pickles &Olive",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "14",
    "resName": "citybalcony",
    "name": "كبة ",
    "name2": "Kibbeh ",
    "price": "3.00",
    "description": "٤ حبات",
    "description2": "4 pieces",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "15",
    "resName": "citybalcony",
    "name": "سمبوسك جبنة ",
    "name2": "Sambousek",
    "price": "2.50",
    "description": "٤ حبات",
    "description2": "4 pieces",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "16",
    "resName": "citybalcony",
    "name": "بطاطا مقلية",
    "name2": "Fries",
    "price": "1.75",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "17",
    "resName": "citybalcony",
    "name": "بطاطا مع جبنة",
    "name2": "Cheesy Fries",
    "price": "2.75",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "18",
    "resName": "citybalcony",
    "name": "يلنجي ",
    "name2": "Ylange ",
    "price": "3.00",
    "description": "٦ حبات",
    "description2": "6pieces",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "19",
    "resName": "citybalcony",
    "name": "فتة مقدوس",
    "name2": "Eggplant Fattah ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "20",
    "resName": "citybalcony",
    "name": "اضافة صوص",
    "name2": "Add Sauce",
    "price": "0.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "21",
    "resName": "citybalcony",
    "name": "قلاية بندورة",
    "name2": "Tomato Qalaiha",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "22",
    "resName": "citybalcony",
    "name": "قلاية بندورة مع لحمة",
    "name2": "Tomato Qalaiha With Meat",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "23",
    "resName": "citybalcony",
    "name": "حمص",
    "name2": "Hummus",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "24",
    "resName": "citybalcony",
    "name": "حمص بيروتي",
    "name2": "Beirut Hummus",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "25",
    "resName": "citybalcony",
    "name": "حمص مع لحمة",
    "name2": "Hummus with meat",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "26",
    "resName": "citybalcony",
    "name": "فول",
    "name2": "Fava Beans ",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "27",
    "resName": "citybalcony",
    "name": "فلافل",
    "name2": "Falafel",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "28",
    "resName": "citybalcony",
    "name": "زيت و زعتر",
    "name2": "Za’atar & Olive Oil",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "30",
    "resName": "citybalcony",
    "name": "دبس و طحينة",
    "name2": "Molasses & Tahini",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "31",
    "resName": "citybalcony",
    "name": "متبل",
    "name2": "Mutabal with Eggplant",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "32",
    "resName": "citybalcony",
    "name": "متبل باذنجان مع جميد",
    "name2": "Eggplant Mutabal With Jameed",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "33",
    "resName": "citybalcony",
    "name": "بابا غنوج",
    "name2": "Baba Ghanoush",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "34",
    "resName": "citybalcony",
    "name": "لبنة جرشية",
    "name2": "Jarsh Labneh ",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "35",
    "resName": "citybalcony",
    "name": "لبنة مدحبرة",
    "name2": "Labneh Balls",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "36",
    "resName": "citybalcony",
    "name": "متبل الأفوكادو",
    "name2": "Avocado Mutabal",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "37",
    "resName": "citybalcony",
    "name": "مربى و قشطة",
    "name2": "Jam & Cream",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "38",
    "resName": "citybalcony",
    "name": "مربى و زبده",
    "name2": "Jam & Butter",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "39",
    "resName": "citybalcony",
    "name": "حلاوة و سمنة",
    "name2": "Halva With Ghee",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "40",
    "resName": "citybalcony",
    "name": "مقدوس",
    "name2": "Maqdos",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "41",
    "resName": "citybalcony",
    "name": "كشكة مقدوس ",
    "name2": "Maqdos kishkh",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "42",
    "resName": "citybalcony",
    "name": "اوملت",
    "name2": "Omelet",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "43",
    "resName": "citybalcony",
    "name": "بيض مع نقانق",
    "name2": "Eggs With Sausage",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "44",
    "resName": "citybalcony",
    "name": "بيض مع جبنة",
    "name2": "Eggs With Cheese",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "45",
    "resName": "citybalcony",
    "name": "بيض مقلي",
    "name2": "Fried Eggs",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "46",
    "resName": "citybalcony",
    "name": "بيض عيون",
    "name2": "Eye Eggs",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "47",
    "resName": "citybalcony",
    "name": "شكشوكة",
    "name2": "Shakshuka",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "48",
    "resName": "citybalcony",
    "name": "جبنة بيضاء مقلية",
    "name2": "Fried Local Cheese",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "49",
    "resName": "citybalcony",
    "name": "جبنة بيضاء مشوية",
    "name2": "Grilled Local Cheese",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "50",
    "resName": "citybalcony",
    "name": "كبدة دجاج",
    "name2": "Chicken Liver ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "51",
    "resName": "citybalcony",
    "name": "فطر مع لحمة",
    "name2": "Mushroom with Meat",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "52",
    "resName": "citybalcony",
    "name": "فطر مع نقانق",
    "name2": "Mushroom with Sausage ",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "53",
    "resName": "citybalcony",
    "name": "زهرة و باذنجان مقلي",
    "name2": "Fried Eggplant & Cauliflower",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "54",
    "resName": "citybalcony",
    "name": "مفركة مع بيض",
    "name2": "Mufarakah with Eggs ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "55",
    "resName": "citybalcony",
    "name": "مفركة بطاطا مع بصل",
    "name2": "Mufarakah with Onions",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "56",
    "resName": "citybalcony",
    "name": "تبولة",
    "name2": "Tabbouleh",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "57",
    "resName": "citybalcony",
    "name": "فتوش",
    "name2": "Fattoush",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "58",
    "resName": "citybalcony",
    "name": "سلطة يونانية",
    "name2": "Greek Salad ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "59",
    "resName": "citybalcony",
    "name": "سلطة سيزر",
    "name2": "Caesar Salad ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "60",
    "resName": "citybalcony",
    "name": "سلطة سيزر مع دجاج",
    "name2": "Chicken Caesar Salad",
    "price": "4.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "61",
    "resName": "citybalcony",
    "name": "جرجير",
    "name2": "Watercress Salad",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "62",
    "resName": "citybalcony",
    "name": "سلطة عربية",
    "name2": "Arabic Salad",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "63",
    "resName": "citybalcony",
    "name": "سلطة فلاحية",
    "name2": "Flahiha Salad ",
    "price": "2.00",
    "description": "طماطم مع بصل\r\n",
    "description2": "Tomato with Onion ",
    "imageURL": "",
    "category": "Salad",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "64",
    "resName": "citybalcony",
    "name": "صاجية لحمة خروف بلدي 250 غرام",
    "name2": "Lamb Saiya, 250g (Local ) ",
    "price": "8.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "65",
    "resName": "citybalcony",
    "name": "حوسة لحمة راس عصفور مع بصل خروف بلدي 250 غرام",
    "name2": "Meat “Asfour” 250g ( local) ",
    "price": "8.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "66",
    "resName": "citybalcony",
    "name": "صينية ريش خروف بلدي 500 غرام",
    "name2": "Tray of Lamb Chops,500g (Local)",
    "price": "12.00",
    "description": "بصل و جزر والبطاطا",
    "description2": "Onions,carrots,potatoes",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "67",
    "resName": "citybalcony",
    "name": " كفتة بالبندورة 250 غرام",
    "name2": "Kofta With Tomatoes,250g",
    "price": "6.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "68",
    "resName": "citybalcony",
    "name": "كفتة بالطحينية 250 غرام",
    "name2": "Kofta With Potato & Tahini, 250g.",
    "price": "6.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "69",
    "resName": "citybalcony",
    "name": "صاجية دجاج بالخضار 250 غرام",
    "name2": "Chicken Sajiya with Vegetables,250g ",
    "price": "5.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "70",
    "resName": "citybalcony",
    "name": "صاجية دجاج بالكريما 250 غرام",
    "name2": "Chicken Sajiya With Garlic & Lemon",
    "price": "6.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "72",
    "resName": "citybalcony",
    "name": "منزلة باذنجان",
    "name2": "Menzaleh with Eggplant",
    "price": "5.00",
    "description": "لحمة مفرومة ، بصل، طماطم\n",
    "description2": "Ground Beef,Onion, Tomato",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "73",
    "resName": "citybalcony",
    "name": "نقانق مع خضار",
    "name2": "Hotdog with Vegetables ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "74",
    "resName": "citybalcony",
    "name": " فتوتتشيني الفريدو",
    "name2": "Fettuccine Alfredo ",
    "price": "3.25",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "75",
    "resName": "citybalcony",
    "name": "فتوتشيني الفريدو بالدجاج",
    "name2": "Fettuccine Chicken Alfredo",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "76",
    "resName": "citybalcony",
    "name": "فريكة بالكريما مع دجاج وفطر",
    "name2": "Freekeh with Cream, chicken & Mushroom ",
    "price": "5.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "77",
    "resName": "citybalcony",
    "name": "جوانح دجاج بلكونة المدينه",
    "name2": "City Balcony Wings",
    "price": "5.00",
    "description": "١٠ قطع",
    "description2": "10 pieces",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "78",
    "resName": "citybalcony",
    "name": "جوانح دجاج بالباربكيو صوص",
    "name2": "Barbecue Wings",
    "price": "5.00",
    "description": "١٠ قطع",
    "description2": "10 pieces",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "79",
    "resName": "citybalcony",
    "name": "جوانح دجاج سويت تشلي صوص",
    "name2": "Sweet Chili Wings",
    "price": "5.00",
    "description": "١٠ قطع",
    "description2": "10 pieces",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "80",
    "resName": "citybalcony",
    "name": "جوانح دجاج بالدينمايت صوص",
    "name2": "Dynamite Wings",
    "price": "5.00",
    "description": "١٠ قطع",
    "description2": "10 pieces",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "81",
    "resName": "citybalcony",
    "name": "جوانح دجاج كرسبي",
    "name2": "Crispy Wings",
    "price": "5.00",
    "description": "١٠ قطع",
    "description2": "10 pieces",
    "imageURL": "",
    "category": "Lunch/dinner",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "82",
    "resName": "citybalcony",
    "name": "وجبة فهيتا",
    "name2": "Fajita With Fries",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Snacks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "83",
    "resName": "citybalcony",
    "name": "وجبة مكسيكان",
    "name2": "Mexican With Fries",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Snacks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "84",
    "resName": "citybalcony",
    "name": "وجبة كريمي زنجر",
    "name2": "Creamy Zinger With Fries",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Snacks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "85",
    "resName": "citybalcony",
    "name": "وجبة هوت دوق",
    "name2": "Hotdog With Fries",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Snacks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "86",
    "resName": "citybalcony",
    "name": "عدس",
    "name2": "Lentil Soup",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soups",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "87",
    "resName": "citybalcony",
    "name": "فريكة",
    "name2": "Freekeh Soup",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soups",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "88",
    "resName": "citybalcony",
    "name": "رشوف",
    "name2": "Rashouf",
    "price": "3.50",
    "description": "عدس، بصل، قمح، جميد",
    "description2": "Lentil, Onion, Wheat & Jameed",
    "imageURL": "",
    "category": "Soups",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "89",
    "resName": "citybalcony",
    "name": "ام علي",
    "name2": "Um-Ali ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "90",
    "resName": "citybalcony",
    "name": "كنافه عصمليه",
    "name2": "Kunafa Osmalia",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "91",
    "resName": "citybalcony",
    "name": "كنافه ناعمه",
    "name2": "Kunafa Na3mh",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "92",
    "resName": "citybalcony",
    "name": "كنافه خشنه",
    "name2": "Kunafa Kheshnh",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "93",
    "resName": "citybalcony",
    "name": "تشيز كيك",
    "name2": "Cheese Cake",
    "price": "3.00",
    "description": "فراوله,توت,كرز",
    "description2": "Strawberry, Blueberry, Cherry",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "94",
    "resName": "citybalcony",
    "name": "نوتيلا تشيز كيك",
    "name2": "Nutella Cheese Cake",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "95",
    "resName": "citybalcony",
    "name": "لوتيس تشيز كيك",
    "name2": "Lotus Cheese Cake",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "96",
    "resName": "citybalcony",
    "name": "شوكليت كيك",
    "name2": "Chocolate Cake",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "97",
    "resName": "citybalcony",
    "name": "شوكليت موس",
    "name2": "Chocolate Mousse",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "98",
    "resName": "citybalcony",
    "name": "براونيز",
    "name2": "Brownies",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "99",
    "resName": "citybalcony",
    "name": "سبستيان",
    "name2": "Sebastian Cake",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "100",
    "resName": "citybalcony",
    "name": "عربية",
    "name2": "Arabic Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "101",
    "resName": "citybalcony",
    "name": "اوريو",
    "name2": "Oreo Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "102",
    "resName": "citybalcony",
    "name": "سنكرز",
    "name2": "Snickers Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "103",
    "resName": "citybalcony",
    "name": "كروكان",
    "name2": "Crocan Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "104",
    "resName": "citybalcony",
    "name": "لوتس",
    "name2": "Lotus Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "105",
    "resName": "citybalcony",
    "name": "تشيز كيك",
    "name2": "Cheesecake Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "106",
    "resName": "citybalcony",
    "name": "شوكلت",
    "name2": "Chocolate Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "107",
    "resName": "citybalcony",
    "name": "فراولة",
    "name2": "Strawberry Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "108",
    "resName": "citybalcony",
    "name": "منجا",
    "name2": "Mango Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "109",
    "resName": "citybalcony",
    "name": "ڤانيلا",
    "name2": "Vanilla Ice Cream",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Ice Cream",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "110",
    "resName": "citybalcony",
    "name": "قهوة تركية دبل",
    "name2": "Double\r\nTurkish Coffee",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "111",
    "resName": "citybalcony",
    "name": "قهوة تركية سنجل",
    "name2": "Single\r\nTurkish Coffee",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "112",
    "resName": "citybalcony",
    "name": "قهوة فرنسية",
    "name2": "French Coffee",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "113",
    "resName": "citybalcony",
    "name": "اسبرسو",
    "name2": "Espresso",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "114",
    "resName": "citybalcony",
    "name": "هوت شوكلت",
    "name2": "Hot Chocolate",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "115",
    "resName": "citybalcony",
    "name": "نسكافيه",
    "name2": "Nescafe",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "116",
    "resName": "citybalcony",
    "name": "كاباتشينو",
    "name2": "Cappuccino",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "117",
    "resName": "citybalcony",
    "name": "كاباتشينو مع كراميل",
    "name2": "Caramel & Cappuccino",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "118",
    "resName": "citybalcony",
    "name": "كاباتشينو مع بندق",
    "name2": "Hazelnut & Cappuccino",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "119",
    "resName": "citybalcony",
    "name": "لاتيه",
    "name2": "Latte",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "120",
    "resName": "citybalcony",
    "name": "لاتيه كراميل",
    "name2": "Latte Caramel",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "121",
    "resName": "citybalcony",
    "name": "لاتيه توفي",
    "name2": "Toffee Latte",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "122",
    "resName": "citybalcony",
    "name": "موكا",
    "name2": "Mocha",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "123",
    "resName": "citybalcony",
    "name": "اميركان",
    "name2": "American",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "124",
    "resName": "citybalcony",
    "name": "اميركانو",
    "name2": "Americano",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "125",
    "resName": "citybalcony",
    "name": "نسكافيه بلاك",
    "name2": "Nescafé Black",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "126",
    "resName": "citybalcony",
    "name": "سبانش لاتيه",
    "name2": "Spanish Latte",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "128",
    "resName": "citybalcony",
    "name": "سحلب",
    "name2": "Sahlab",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Hot Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "129",
    "resName": "citybalcony",
    "name": "شاي",
    "name2": "Arabic Tea",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "130",
    "resName": "citybalcony",
    "name": "مستكة",
    "name2": "Mastic",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "131",
    "resName": "citybalcony",
    "name": "زهورات",
    "name2": "Zhorat",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "132",
    "resName": "citybalcony",
    "name": "بابونج",
    "name2": "Chamomile",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "133",
    "resName": "citybalcony",
    "name": "يانسون",
    "name2": "Anise",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "134",
    "resName": "citybalcony",
    "name": "زنجبيل",
    "name2": "Ginger",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "135",
    "resName": "citybalcony",
    "name": "شاي كرك",
    "name2": "Karak Tea",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Tea",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "136",
    "resName": "citybalcony",
    "name": "برتقال",
    "name2": "Orange",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "137",
    "resName": "citybalcony",
    "name": "فراوله",
    "name2": "Strawberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "138",
    "resName": "citybalcony",
    "name": "مانجا",
    "name2": "Mango",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "140",
    "resName": "citybalcony",
    "name": "كيوي و منجا",
    "name2": "Kiwi & Mango",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "141",
    "resName": "citybalcony",
    "name": "كيوي و ليمون",
    "name2": "Kiwi & Lemon",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "142",
    "resName": "citybalcony",
    "name": "ليمون و نعنع",
    "name2": "Lemon & Mint ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "143",
    "resName": "citybalcony",
    "name": "صودا",
    "name2": "Soda",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "144",
    "resName": "citybalcony",
    "name": "باربيكان",
    "name2": "Barbican",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "145",
    "resName": "citybalcony",
    "name": "ريد بول",
    "name2": "Red Bull ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "146",
    "resName": "citybalcony",
    "name": "فايروس",
    "name2": "Virus",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "147",
    "resName": "citybalcony",
    "name": "بيبسي",
    "name2": "Pepsi",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "148",
    "resName": "citybalcony",
    "name": "سفن اب",
    "name2": "7Up",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "149",
    "resName": "citybalcony",
    "name": "ميراندا",
    "name2": "Miranda",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "150",
    "resName": "citybalcony",
    "name": " بوم بوم",
    "name2": "Boom Boom",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "151",
    "resName": "citybalcony",
    "name": "مياه غازية",
    "name2": "Carbonated Water",
    "price": "1.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "152",
    "resName": "citybalcony",
    "name": "مياه ",
    "name2": "Bottled Water",
    "price": "0.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "153",
    "resName": "citybalcony",
    "name": "عيران",
    "name2": "Ayran",
    "price": "1.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Soft drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "154",
    "resName": "citybalcony",
    "name": "باشن فروت",
    "name2": "Passion Fruit",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "155",
    "resName": "citybalcony",
    "name": "مانجا",
    "name2": "Mango",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "156",
    "resName": "citybalcony",
    "name": "تفاح",
    "name2": "Apple",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "157",
    "resName": "citybalcony",
    "name": "كيوي",
    "name2": "Kiwi",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "158",
    "resName": "citybalcony",
    "name": "انانس",
    "name2": "Pineapple",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "159",
    "resName": "citybalcony",
    "name": "بلوبيري",
    "name2": "Blueberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "160",
    "resName": "citybalcony",
    "name": "رمان",
    "name2": "Pomegranate",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "161",
    "resName": "citybalcony",
    "name": "فراولة",
    "name2": "Strawberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "162",
    "resName": "citybalcony",
    "name": "ليتشي",
    "name2": "Lychee",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "163",
    "resName": "citybalcony",
    "name": "مانجا +باشن فروت",
    "name2": "Mango & Passion Fruit",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "164",
    "resName": "citybalcony",
    "name": "تفاح + فراولة",
    "name2": "Apple & Strawberry ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "165",
    "resName": "citybalcony",
    "name": "بطيخ",
    "name2": "Watermelon",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "166",
    "resName": "citybalcony",
    "name": "بلو كوراساو",
    "name2": "Blue Curacao ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "167",
    "resName": "citybalcony",
    "name": "جراندين",
    "name2": "Grandin",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "168",
    "resName": "citybalcony",
    "name": "بلكونة المدينة مهيتوا",
    "name2": "City Balcony Mojito",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Mojito",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "169",
    "resName": "citybalcony",
    "name": "عربية",
    "name2": "Arabic",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "170",
    "resName": "citybalcony",
    "name": "شوكليت",
    "name2": "Chocolate",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "171",
    "resName": "citybalcony",
    "name": "اوريو",
    "name2": "Oreo",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "172",
    "resName": "citybalcony",
    "name": "سنيكرز",
    "name2": "Snickers",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "173",
    "resName": "citybalcony",
    "name": "كروكان",
    "name2": "Crocan",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "174",
    "resName": "citybalcony",
    "name": "لوتس",
    "name2": "Lotus",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "175",
    "resName": "citybalcony",
    "name": "فراولة",
    "name2": "Strawberry",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "176",
    "resName": "citybalcony",
    "name": "منجا",
    "name2": "Mango\r\n",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "177",
    "resName": "citybalcony",
    "name": "ڤانيلا",
    "name2": "Vanilla",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "178",
    "resName": "citybalcony",
    "name": " تشيز كيك",
    "name2": "Cheesecake",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "179",
    "resName": "citybalcony",
    "name": "فراب كراميل",
    "name2": "Frapp Caramel",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "183",
    "resName": "citybalcony",
    "name": "فراب شوكليت",
    "name2": "Frapp Chocolate",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "184",
    "resName": "citybalcony",
    "name": "بلكونة المدينة ميلك شيك",
    "name2": "City Balcony Milkshake ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshake",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "195",
    "resName": "citybalcony",
    "name": "باشن فروت و منجا وبابلز",
    "name2": "Passion Fruit, Mango\r\n& Boba",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "196",
    "resName": "citybalcony",
    "name": "باشن فروت",
    "name2": "Passion Fruit",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "197",
    "resName": "citybalcony",
    "name": "سموذي تارو وبابلز",
    "name2": "Taro & Boba",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "198",
    "resName": "citybalcony",
    "name": "تارو ",
    "name2": "Taro ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "199",
    "resName": "citybalcony",
    "name": "سموذي فراولة و بابلز",
    "name2": "Strawberry & Boba",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "200",
    "resName": "citybalcony",
    "name": "منجا",
    "name2": "Mango ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "202",
    "resName": "citybalcony",
    "name": "تفاح",
    "name2": "Apple",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "203",
    "resName": "citybalcony",
    "name": "فراولة",
    "name2": "Strawberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "204",
    "resName": "citybalcony",
    "name": "ليمون و نعنع ",
    "name2": "lemon & Mint",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "205",
    "resName": "citybalcony",
    "name": "ليمون  ",
    "name2": "lemon ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "206",
    "resName": "citybalcony",
    "name": "بلكونة المدينة سموذي",
    "name2": "City Balcony Smoothie",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothie",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "207",
    "resName": "citybalcony",
    "name": "ايس كوفي",
    "name2": "Iced Coffee",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "208",
    "resName": "citybalcony",
    "name": "ايس امريكان",
    "name2": "Iced American ",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "209",
    "resName": "citybalcony",
    "name": "ايس موكا",
    "name2": "Iced Mocha",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "210",
    "resName": "citybalcony",
    "name": "ايس توفي",
    "name2": "Iced Toffee",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "211",
    "resName": "citybalcony",
    "name": "ايس لاتيه كارمل",
    "name2": "Iced Caramel Latte",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "212",
    "resName": "citybalcony",
    "name": "ايس كارمل مكياتو",
    "name2": "Iced Caramel Macchiato ",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "213",
    "resName": "citybalcony",
    "name": "ايس سبانش لاتيه",
    "name2": "Iced Spanish Latte",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "214",
    "resName": "citybalcony",
    "name": "ايس تي خوخ",
    "name2": "Iced Tea Peach ",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "215",
    "resName": "citybalcony",
    "name": "ايس تي ليمون",
    "name2": "Iced Tea Lemon",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "216",
    "resName": "citybalcony",
    "name": "ايس تي باشن فروت",
    "name2": "Iced Tea Passion Fruit",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Iced Coffee",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "217",
    "resName": "citybalcony",
    "name": "تفاحتين نخلة",
    "name2": "Double Apple Palm ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "218",
    "resName": "citybalcony",
    "name": "تفاحتين مزايا",
    "name2": "Double Apple Mazaia",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "219",
    "resName": "citybalcony",
    "name": "علكة و قرفة",
    "name2": "Gum & Cinnamon",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "220",
    "resName": "citybalcony",
    "name": "علكة و نعنع",
    "name2": "Gum & mint",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "221",
    "resName": "citybalcony",
    "name": "علكة مستكة",
    "name2": "Mastic Gum ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "222",
    "resName": "citybalcony",
    "name": "ليمون و نعنع",
    "name2": "Lemon & Mint ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "223",
    "resName": "citybalcony",
    "name": "بطيخ و نعنع",
    "name2": "Watermelon & Mint ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "224",
    "resName": "citybalcony",
    "name": "عنب وتوت",
    "name2": "Grape & Berries ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "225",
    "resName": "citybalcony",
    "name": "بلوبيري",
    "name2": "Blueberry",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "226",
    "resName": "citybalcony",
    "name": "عنب و نعنع",
    "name2": "Grape & Mint ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "227",
    "resName": "citybalcony",
    "name": "سبشل دراق و منجا",
    "name2": "Special Peach & Mango",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "228",
    "resName": "citybalcony",
    "name": "كاندي دروبس",
    "name2": "Candy Drops",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "229",
    "resName": "citybalcony",
    "name": "روبي كرش",
    "name2": "Ruby Crushe",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "230",
    "resName": "citybalcony",
    "name": "love ",
    "name2": "love",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "231",
    "resName": "citybalcony",
    "name": "تفاح و بطيخ ايس",
    "name2": "Apple & Watermelon Ice",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "232",
    "resName": "citybalcony",
    "name": "ايس كريم عربية",
    "name2": "Arabic Ice Cream ",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "233",
    "resName": "citybalcony",
    "name": "بلكونة المدينة",
    "name2": "City Balcony Special",
    "price": "5.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "234",
    "resName": "citybalcony",
    "name": "تجديد الراس",
    "name2": "Head renewal",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "235",
    "resName": "citybalcony",
    "name": "خدمة ارجيلة",
    "name2": "Sheshah Service",
    "price": "2.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Sheshah",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "236",
    "resName": "citybalcony",
    "name": "ليمون",
    "name2": "Lemonade",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Fresh Juices",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "237",
    "resName": "citybalcony",
    "name": "موز ",
    "name2": "Banana ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "238",
    "resName": "citybalcony",
    "name": "بينا كولادا",
    "name2": "Pana Colada",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "243",
    "resName": "citybalcony",
    "name": "برتقال و فراولة",
    "name2": "Orange & Strawberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "244",
    "resName": "citybalcony",
    "name": "موز و فراولة",
    "name2": "Strawberry & Banana ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "245",
    "resName": "citybalcony",
    "name": "فراولة و نعنع",
    "name2": "Strawberry & Mint",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "246",
    "resName": "citybalcony",
    "name": "مانجا و فراولة و موز",
    "name2": "Mango ,Strawberry & Banana ",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "247",
    "resName": "citybalcony",
    "name": "مكس بيري وڤانيلا",
    "name2": "Mixed Berry & Vanilla",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "248",
    "resName": "citybalcony",
    "name": "افوكادو و عسل و مكسرات و قشطة",
    "name2": "Avocado, Honey, Nuts & cream",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "249",
    "resName": "citybalcony",
    "name": "بلكونة المدينة كوكتيل",
    "name2": "City Balcony Cocktail",
    "price": "4.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "250",
    "resName": "citybalcony",
    "name": "سلطة بلكونة المدينة",
    "name2": "City Balcony Salad",
    "price": "4.00",
    "description": "خس، بندورة، جرجير، زيتون أخضر، جميد، بصل",
    "description2": "Lettuce, tomatoes, arugula, green olives, jameed, onion",
    "imageURL": "",
    "category": "Salads",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "251",
    "resName": "citybalcony",
    "name": "ايس بستاشيو",
    "name2": "Iced Pistachio",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cold Drinks",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "252",
    "resName": "citybalcony",
    "name": "بطاطس ودجز حارة",
    "name2": "Spicy Potato Wedges",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "253",
    "resName": "citybalcony",
    "name": "بطاطس ودجز",
    "name2": "Potato Wedges",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Appetizers",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "254",
    "resName": "citybalcony",
    "name": "بيض مع نقانق",
    "name2": "Egg with Hotdog",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "255",
    "resName": "citybalcony",
    "name": "فطر مع نقانق",
    "name2": "Mushroom with Hotdog",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Breakfast",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "256",
    "resName": "citybalcony",
    "name": "صينية ريش خروف بلدي 500 غرام",
    "name2": "Local Lamb Chops Tray 500g",
    "price": "12.00",
    "description": "بصل وبطاطا",
    "description2": "Onions and potatoes",
    "imageURL": "",
    "category": "Lunch",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "257",
    "resName": "citybalcony",
    "name": "صاجية دجاج مطفيه بالثوم والليمون",
    "name2": "Chicken Sajiya with Garlic & Lemon",
    "price": "5.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Lunch",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "258",
    "resName": "citybalcony",
    "name": "سلطة الذرة",
    "name2": "Corn Salad",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salads",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "259",
    "resName": "citybalcony",
    "name": "سلطة الشمندر",
    "name2": "Beetroot Salad",
    "price": "2.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Salads",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "260",
    "resName": "citybalcony",
    "name": "ابل باي",
    "name2": "Apple Pie",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Desserts",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "261",
    "resName": "citybalcony",
    "name": "بلو رازبيري",
    "name2": "Blue Raspberry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothies",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "262",
    "resName": "citybalcony",
    "name": "مكس بيري",
    "name2": "Mixed Berry",
    "price": "3.00",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Smoothies",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "263",
    "resName": "citybalcony",
    "name": "مكس بالبوظة العربية وبلوبيري",
    "name2": "Mix with Arabic Ice Cream & Blueberry",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Cocktails",
    "isOffer": "no",
    "offerVal": "0"
  },
  {
    "id": "264",
    "resName": "citybalcony",
    "name": "مكس بيري بجوز الهند",
    "name2": "Mixed Berry with Coconut",
    "price": "3.50",
    "description": "",
    "description2": "",
    "imageURL": "",
    "category": "Milkshakes",
    "isOffer": "no",
    "offerVal": "0"
  }
];
